package com.guidance.service;

import com.guidance.model.*;
import com.guidance.repository.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

@Service
@Transactional
public class ProjectGroupService {

    private final ProjectGroupRepository groupRepository;
    private final UserRepository userRepository;
    private final ConnectionRequestRepository requestRepository;
    private final ChatMessageRepository messageRepository;

    public ProjectGroupService(ProjectGroupRepository groupRepository, UserRepository userRepository,
                               ConnectionRequestRepository requestRepository, ChatMessageRepository messageRepository) {
        this.groupRepository = groupRepository;
        this.userRepository = userRepository;
        this.requestRepository = requestRepository;
        this.messageRepository = messageRepository;
    }

    public ProjectGroup createGroup(String groupName, String techStack, Set<Long> memberIds, String creatorEmail) {
        ProjectGroup group = new ProjectGroup();
        group.setGroupName(groupName);
        group.setTechStack(techStack);
        group.setCreatedBy(creatorEmail);

        // findById natively returns Optional<User>, so orElseThrow remains valid here
        Set<User> members = memberIds.stream()
                .map(id -> userRepository.findById(id).orElseThrow(() -> new RuntimeException("User not found: " + id)))
                .collect(Collectors.toSet());

        // Refactored to handle direct User return type with a null check
        User creator = userRepository.findByEmail(creatorEmail);
        if (creator != null) {
            members.add(creator);
        }
        group.setMembers(members);

        return groupRepository.save(group);
    }

    public List<ProjectGroup> getUserGroups(String email) {
        // Refactored from Optional handling to direct null verification
        User user = userRepository.findByEmail(email);
        if (user == null) {
            throw new RuntimeException("User not found with email: " + email);
        }
        return groupRepository.findActiveGroupsByUserId(user.getId());
    }

    public List<User> getPotentialMentors(Long groupId) {
        ProjectGroup group = groupRepository.findById(groupId).orElseThrow(() -> new RuntimeException("Group not found"));
        Set<Long> memberIds = group.getMembers().stream().map(User::getId).collect(Collectors.toSet());

        // Return all system users except those currently belonging to this group
        return userRepository.findAll().stream()
                .filter(user -> !memberIds.contains(user.getId()))
                .collect(Collectors.toList());
    }

    public void sendMentorRequests(Long groupId, List<Long> mentorIds) {
        ProjectGroup group = groupRepository.findById(groupId).orElseThrow(() -> new RuntimeException("Group not found"));
        for (Long mentorId : mentorIds) {
            User mentor = userRepository.findById(mentorId).orElseThrow(() -> new RuntimeException("Mentor not found"));
            ConnectionRequest request = new ConnectionRequest();
            request.setGroup(group);
            request.setMentor(mentor);
            requestRepository.save(request);
        }
    }

    public List<ConnectionRequest> getPendingRequestsForUser(String email) {
        // Refactored to handle raw User return type
        User user = userRepository.findByEmail(email);
        if (user == null) {
            throw new RuntimeException("User not found with email: " + email);
        }
        return requestRepository.findPendingRequestsByMentorEmail(email); // -1 is Pending
    }

//    public void acceptRequest(Long requestId) {
//        ConnectionRequest request = requestRepository.findById(requestId)
//                .orElseThrow(() -> new RuntimeException("Request not found"));
//
//        ProjectGroup group = request.getGroup();
//        User mentor = request.getMentor();
//
//        // Bind mentor directly to target table column
//        group.setMentor(mentor);
//        groupRepository.save(group);
//
//        // Accept current invitation instance
//        request.setStatus(1);
//        requestRepository.save(request);
//
//        // Cascade cleanup: Automatically purge all concurrent pending request options generated by this specific group
//        List<ConnectionRequest> siblingRequests = requestRepository.findByGroupIdAndStatus(group.getId(), -1);
//        requestRepository.deleteAll(siblingRequests);
//    }

    public void acceptRequest(Long requestId) {
        ConnectionRequest request = requestRepository.findById(requestId)
                .orElseThrow(() -> new RuntimeException("Request not found"));

        ProjectGroup group = request.getGroup();
        User mentor = request.getMentor();

        // Bind mentor directly to target table column
        group.setMentor(mentor);

//        // 🆕 Add mentor's user ID to the cross-join table (group_members)
//        if (group.getMembers() != null) {
//            group.getMembers().add(mentor);
//        }

        groupRepository.save(group);

        // Accept current invitation instance
        request.setStatus(1);
        requestRepository.save(request);

        // Cascade cleanup
        List<ConnectionRequest> siblingRequests = requestRepository.findByGroupIdAndStatus(group.getId(), -1);
        requestRepository.deleteAll(siblingRequests);
    }

    public void rejectRequest(Long requestId) {
        ConnectionRequest request = requestRepository.findById(requestId)
                .orElseThrow(() -> new RuntimeException("Request not found"));

        // Set state to rejected so it falls out of the mentor's pending list view
        request.setStatus(0);
        requestRepository.save(request);
    }

    public ChatMessage saveMessage(Long groupId, String senderEmail, String content) {
        ProjectGroup group = groupRepository.findById(groupId).orElseThrow(() -> new RuntimeException("Group not found"));

        // Refactored to handle raw User return type
        User sender = userRepository.findByEmail(senderEmail);
        if (sender == null) {
            throw new RuntimeException("Sender not found with email: " + senderEmail);
        }

        ChatMessage message = new ChatMessage();
        message.setGroup(group);
        message.setSender(sender);
        message.setContent(content);
        return messageRepository.save(message);
    }

    public List<ChatMessage> getGroupMessages(Long groupId) {
        return messageRepository.findByGroupIdOrderByTimestampAsc(groupId);
    }
}